"""change firebase uid length to 28

Revision ID: af60e842d4e4
Revises: da8bf6a36467
Create Date: 2026-03-08 14:40:50.625029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af60e842d4e4'
down_revision = 'da8bf6a36467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=28),
               existing_nullable=True)

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=28),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.String(length=28),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.String(length=28),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
