"""add model to messages

Revision ID: af8d960f9c3b
Revises: 8ba09400eba1
Create Date: 2026-03-04 12:37:27.998108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8d960f9c3b'
down_revision = '8ba09400eba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('message_index',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('model')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
