"""add status to messages

Revision ID: da8bf6a36467
Revises: 039368e3326a
Create Date: 2026-03-08 09:09:07.952020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8bf6a36467'
down_revision = '039368e3326a'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "messages",
        sa.Column("status", sa.String(length=20), nullable=False, server_default="completed")
    )

    op.execute("UPDATE messages SET status = 'completed' WHERE status IS NULL")

    op.alter_column("messages", "status", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
